### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by zach-adams** [nounoursheureux/about-blank#6]
It would be cool if you could get some of the configurations working for OS X. I've installed it and this is what I see:
http://i.imgur.com/uKSMfAb.png

Although besides that it works fine. Also a note on installing it for other OS X users, you have to make sure you've installed MPC with:

`brew install mpc`

Then follow the directions in this guide to install MPD: http://mpd.wikia.com/wiki/Mpd_on_OS_X_Snow_Leopard

**Comment by wbrbr** [comment]
I pushed a `server-mac.js` on the test branch, but I don't have a Mac so I don't know if it works. It needs `osascript-node` to fetch information from iTunes.

**Comment by frm** [comment]
I've picked this up as I was facing similar problems.

You can check the progress in [here](https://github.com/frmendes/about-blank/tree/test)

When I started it was something like this:
![sample](https://cloud.githubusercontent.com/assets/4325027/6643470/5afb24ea-c9a4-11e4-8f91-9ea8049e662a.png)

I fixed a few bugs with iTunes:
- it crashed when I started the server and iTunes wasn't running
- it had issues with running when iTunes was paused/stopped
- when iTunes isn't running it doesn't display anything to avoid confusion (can change it if you want, like send an empty string or so)

I also fixed the description for the disk, but I don't know if it should remain like that or more complete.

As a final touch, I had it collect the artist name but I can also remove if it if you want.

Here's how I have it so far:

![sample2](https://cloud.githubusercontent.com/assets/4325027/6643531/d5e631c2-c9a4-11e4-83da-c54d8681d4e1.png)

If you want me to change anything or make a PR, I'll be glad to.

**Comment by wbrbr** [comment]
Thanks for your help :+1:  . Actually I think you should remove `node-osascript` from the dependencies in the config.json, and I'll add a step in the installation process in the README instead (or if you know a way to have OS-specific dependencies please tell me). 
Or maybe it would be better to make a Mac-specific git branch.

**Comment by frm** [comment]
I actually agree with you regarding `node-osascript`. I'll remove as soon as I can.

A Mac-specific branch can be a bit confusing for a dependency that can be fixed with one `npm install`, IMO. Maybe specify it in the README, since OS X users already have to install a few things, as @zach-adams previously said.

**Comment by wbrbr** [comment]
OK, I updated the README in the test branch. If everything works fine you should make a PR.
